// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AddressCreate address create
//
// swagger:model AddressCreate
type AddressCreate struct {

	// The name of the address
	// Required: true
	Name *string `json:"name"`

	// The smartlocks for this address
	// Required: true
	SmartlockIds []int64 `json:"smartlockIds"`
}

// Validate validates this address create
func (m *AddressCreate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSmartlockIds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AddressCreate) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *AddressCreate) validateSmartlockIds(formats strfmt.Registry) error {

	if err := validate.Required("smartlockIds", "body", m.SmartlockIds); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this address create based on context it is used
func (m *AddressCreate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AddressCreate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AddressCreate) UnmarshalBinary(b []byte) error {
	var res AddressCreate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
