// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AddressTokenInfo address token info
//
// swagger:model AddressTokenInfo
type AddressTokenInfo struct {

	// The address name
	// Required: true
	AddressName *string `json:"addressName"`

	// The id
	// Required: true
	ID *string `json:"id"`

	// The associated smartlock names
	// Required: true
	SmartlockNames []string `json:"smartlockNames"`
}

// Validate validates this address token info
func (m *AddressTokenInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAddressName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSmartlockNames(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AddressTokenInfo) validateAddressName(formats strfmt.Registry) error {

	if err := validate.Required("addressName", "body", m.AddressName); err != nil {
		return err
	}

	return nil
}

func (m *AddressTokenInfo) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *AddressTokenInfo) validateSmartlockNames(formats strfmt.Registry) error {

	if err := validate.Required("smartlockNames", "body", m.SmartlockNames); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this address token info based on context it is used
func (m *AddressTokenInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AddressTokenInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AddressTokenInfo) UnmarshalBinary(b []byte) error {
	var res AddressTokenInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
