// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CompletableFutureListAPIKey completable future list Api key
//
// swagger:model CompletableFutureListApiKey
type CompletableFutureListAPIKey struct {

	// cancelled
	Cancelled bool `json:"cancelled,omitempty"`

	// completed exceptionally
	CompletedExceptionally bool `json:"completedExceptionally,omitempty"`

	// done
	Done bool `json:"done,omitempty"`

	// number of dependents
	NumberOfDependents int32 `json:"numberOfDependents,omitempty"`
}

// Validate validates this completable future list Api key
func (m *CompletableFutureListAPIKey) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this completable future list Api key based on context it is used
func (m *CompletableFutureListAPIKey) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CompletableFutureListAPIKey) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CompletableFutureListAPIKey) UnmarshalBinary(b []byte) error {
	var res CompletableFutureListAPIKey
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
