// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ScheduledExecutorService scheduled executor service
//
// swagger:model ScheduledExecutorService
type ScheduledExecutorService struct {

	// shutdown
	Shutdown bool `json:"shutdown,omitempty"`

	// terminated
	Terminated bool `json:"terminated,omitempty"`
}

// Validate validates this scheduled executor service
func (m *ScheduledExecutorService) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this scheduled executor service based on context it is used
func (m *ScheduledExecutorService) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ScheduledExecutorService) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ScheduledExecutorService) UnmarshalBinary(b []byte) error {
	var res ScheduledExecutorService
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
