// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewServiceResourceGetGetParams creates a new ServiceResourceGetGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewServiceResourceGetGetParams() *ServiceResourceGetGetParams {
	return &ServiceResourceGetGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewServiceResourceGetGetParamsWithTimeout creates a new ServiceResourceGetGetParams object
// with the ability to set a timeout on a request.
func NewServiceResourceGetGetParamsWithTimeout(timeout time.Duration) *ServiceResourceGetGetParams {
	return &ServiceResourceGetGetParams{
		timeout: timeout,
	}
}

// NewServiceResourceGetGetParamsWithContext creates a new ServiceResourceGetGetParams object
// with the ability to set a context for a request.
func NewServiceResourceGetGetParamsWithContext(ctx context.Context) *ServiceResourceGetGetParams {
	return &ServiceResourceGetGetParams{
		Context: ctx,
	}
}

// NewServiceResourceGetGetParamsWithHTTPClient creates a new ServiceResourceGetGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewServiceResourceGetGetParamsWithHTTPClient(client *http.Client) *ServiceResourceGetGetParams {
	return &ServiceResourceGetGetParams{
		HTTPClient: client,
	}
}

/*
ServiceResourceGetGetParams contains all the parameters to send to the API endpoint

	for the service resource get get operation.

	Typically these are written to a http.Request.
*/
type ServiceResourceGetGetParams struct {

	/* ServiceID.

	   The service id
	*/
	ServiceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the service resource get get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ServiceResourceGetGetParams) WithDefaults() *ServiceResourceGetGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the service resource get get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ServiceResourceGetGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the service resource get get params
func (o *ServiceResourceGetGetParams) WithTimeout(timeout time.Duration) *ServiceResourceGetGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the service resource get get params
func (o *ServiceResourceGetGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the service resource get get params
func (o *ServiceResourceGetGetParams) WithContext(ctx context.Context) *ServiceResourceGetGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the service resource get get params
func (o *ServiceResourceGetGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the service resource get get params
func (o *ServiceResourceGetGetParams) WithHTTPClient(client *http.Client) *ServiceResourceGetGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the service resource get get params
func (o *ServiceResourceGetGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithServiceID adds the serviceID to the service resource get get params
func (o *ServiceResourceGetGetParams) WithServiceID(serviceID string) *ServiceResourceGetGetParams {
	o.SetServiceID(serviceID)
	return o
}

// SetServiceID adds the serviceId to the service resource get get params
func (o *ServiceResourceGetGetParams) SetServiceID(serviceID string) {
	o.ServiceID = serviceID
}

// WriteToRequest writes these params to a swagger request
func (o *ServiceResourceGetGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param serviceId
	if err := r.SetPathParam("serviceId", o.ServiceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
