// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/leonnicolas/nupin/api/nuki/models"
)

// ServicesResourceGetGetReader is a Reader for the ServicesResourceGetGet structure.
type ServicesResourceGetGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ServicesResourceGetGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewServicesResourceGetGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewServicesResourceGetGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /service] ServicesResource_get_get", response, response.Code())
	}
}

// NewServicesResourceGetGetOK creates a ServicesResourceGetGetOK with default headers values
func NewServicesResourceGetGetOK() *ServicesResourceGetGetOK {
	return &ServicesResourceGetGetOK{}
}

/*
ServicesResourceGetGetOK describes a response with status code 200, with default header values.

successful operation
*/
type ServicesResourceGetGetOK struct {
	Payload []*models.Service
}

// IsSuccess returns true when this services resource get get o k response has a 2xx status code
func (o *ServicesResourceGetGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this services resource get get o k response has a 3xx status code
func (o *ServicesResourceGetGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this services resource get get o k response has a 4xx status code
func (o *ServicesResourceGetGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this services resource get get o k response has a 5xx status code
func (o *ServicesResourceGetGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this services resource get get o k response a status code equal to that given
func (o *ServicesResourceGetGetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the services resource get get o k response
func (o *ServicesResourceGetGetOK) Code() int {
	return 200
}

func (o *ServicesResourceGetGetOK) Error() string {
	return fmt.Sprintf("[GET /service][%d] servicesResourceGetGetOK  %+v", 200, o.Payload)
}

func (o *ServicesResourceGetGetOK) String() string {
	return fmt.Sprintf("[GET /service][%d] servicesResourceGetGetOK  %+v", 200, o.Payload)
}

func (o *ServicesResourceGetGetOK) GetPayload() []*models.Service {
	return o.Payload
}

func (o *ServicesResourceGetGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServicesResourceGetGetUnauthorized creates a ServicesResourceGetGetUnauthorized with default headers values
func NewServicesResourceGetGetUnauthorized() *ServicesResourceGetGetUnauthorized {
	return &ServicesResourceGetGetUnauthorized{}
}

/*
ServicesResourceGetGetUnauthorized describes a response with status code 401, with default header values.

Not authorized
*/
type ServicesResourceGetGetUnauthorized struct {
}

// IsSuccess returns true when this services resource get get unauthorized response has a 2xx status code
func (o *ServicesResourceGetGetUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this services resource get get unauthorized response has a 3xx status code
func (o *ServicesResourceGetGetUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this services resource get get unauthorized response has a 4xx status code
func (o *ServicesResourceGetGetUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this services resource get get unauthorized response has a 5xx status code
func (o *ServicesResourceGetGetUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this services resource get get unauthorized response a status code equal to that given
func (o *ServicesResourceGetGetUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the services resource get get unauthorized response
func (o *ServicesResourceGetGetUnauthorized) Code() int {
	return 401
}

func (o *ServicesResourceGetGetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /service][%d] servicesResourceGetGetUnauthorized ", 401)
}

func (o *ServicesResourceGetGetUnauthorized) String() string {
	return fmt.Sprintf("[GET /service][%d] servicesResourceGetGetUnauthorized ", 401)
}

func (o *ServicesResourceGetGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
