// Code generated by go-swagger; DO NOT EDIT.

package advanced_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DecentralWebhookResourceDeleteDeleteReader is a Reader for the DecentralWebhookResourceDeleteDelete structure.
type DecentralWebhookResourceDeleteDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DecentralWebhookResourceDeleteDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDecentralWebhookResourceDeleteDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDecentralWebhookResourceDeleteDeleteUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDecentralWebhookResourceDeleteDeleteForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /api/decentralWebhook/{id}] DecentralWebhookResource_delete_delete", response, response.Code())
	}
}

// NewDecentralWebhookResourceDeleteDeleteNoContent creates a DecentralWebhookResourceDeleteDeleteNoContent with default headers values
func NewDecentralWebhookResourceDeleteDeleteNoContent() *DecentralWebhookResourceDeleteDeleteNoContent {
	return &DecentralWebhookResourceDeleteDeleteNoContent{}
}

/*
DecentralWebhookResourceDeleteDeleteNoContent describes a response with status code 204, with default header values.

Ok
*/
type DecentralWebhookResourceDeleteDeleteNoContent struct {
}

// IsSuccess returns true when this decentral webhook resource delete delete no content response has a 2xx status code
func (o *DecentralWebhookResourceDeleteDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this decentral webhook resource delete delete no content response has a 3xx status code
func (o *DecentralWebhookResourceDeleteDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this decentral webhook resource delete delete no content response has a 4xx status code
func (o *DecentralWebhookResourceDeleteDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this decentral webhook resource delete delete no content response has a 5xx status code
func (o *DecentralWebhookResourceDeleteDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this decentral webhook resource delete delete no content response a status code equal to that given
func (o *DecentralWebhookResourceDeleteDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the decentral webhook resource delete delete no content response
func (o *DecentralWebhookResourceDeleteDeleteNoContent) Code() int {
	return 204
}

func (o *DecentralWebhookResourceDeleteDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/decentralWebhook/{id}][%d] decentralWebhookResourceDeleteDeleteNoContent ", 204)
}

func (o *DecentralWebhookResourceDeleteDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /api/decentralWebhook/{id}][%d] decentralWebhookResourceDeleteDeleteNoContent ", 204)
}

func (o *DecentralWebhookResourceDeleteDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDecentralWebhookResourceDeleteDeleteUnauthorized creates a DecentralWebhookResourceDeleteDeleteUnauthorized with default headers values
func NewDecentralWebhookResourceDeleteDeleteUnauthorized() *DecentralWebhookResourceDeleteDeleteUnauthorized {
	return &DecentralWebhookResourceDeleteDeleteUnauthorized{}
}

/*
DecentralWebhookResourceDeleteDeleteUnauthorized describes a response with status code 401, with default header values.

Not authorized
*/
type DecentralWebhookResourceDeleteDeleteUnauthorized struct {
}

// IsSuccess returns true when this decentral webhook resource delete delete unauthorized response has a 2xx status code
func (o *DecentralWebhookResourceDeleteDeleteUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this decentral webhook resource delete delete unauthorized response has a 3xx status code
func (o *DecentralWebhookResourceDeleteDeleteUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this decentral webhook resource delete delete unauthorized response has a 4xx status code
func (o *DecentralWebhookResourceDeleteDeleteUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this decentral webhook resource delete delete unauthorized response has a 5xx status code
func (o *DecentralWebhookResourceDeleteDeleteUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this decentral webhook resource delete delete unauthorized response a status code equal to that given
func (o *DecentralWebhookResourceDeleteDeleteUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the decentral webhook resource delete delete unauthorized response
func (o *DecentralWebhookResourceDeleteDeleteUnauthorized) Code() int {
	return 401
}

func (o *DecentralWebhookResourceDeleteDeleteUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /api/decentralWebhook/{id}][%d] decentralWebhookResourceDeleteDeleteUnauthorized ", 401)
}

func (o *DecentralWebhookResourceDeleteDeleteUnauthorized) String() string {
	return fmt.Sprintf("[DELETE /api/decentralWebhook/{id}][%d] decentralWebhookResourceDeleteDeleteUnauthorized ", 401)
}

func (o *DecentralWebhookResourceDeleteDeleteUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDecentralWebhookResourceDeleteDeleteForbidden creates a DecentralWebhookResourceDeleteDeleteForbidden with default headers values
func NewDecentralWebhookResourceDeleteDeleteForbidden() *DecentralWebhookResourceDeleteDeleteForbidden {
	return &DecentralWebhookResourceDeleteDeleteForbidden{}
}

/*
DecentralWebhookResourceDeleteDeleteForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type DecentralWebhookResourceDeleteDeleteForbidden struct {
}

// IsSuccess returns true when this decentral webhook resource delete delete forbidden response has a 2xx status code
func (o *DecentralWebhookResourceDeleteDeleteForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this decentral webhook resource delete delete forbidden response has a 3xx status code
func (o *DecentralWebhookResourceDeleteDeleteForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this decentral webhook resource delete delete forbidden response has a 4xx status code
func (o *DecentralWebhookResourceDeleteDeleteForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this decentral webhook resource delete delete forbidden response has a 5xx status code
func (o *DecentralWebhookResourceDeleteDeleteForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this decentral webhook resource delete delete forbidden response a status code equal to that given
func (o *DecentralWebhookResourceDeleteDeleteForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the decentral webhook resource delete delete forbidden response
func (o *DecentralWebhookResourceDeleteDeleteForbidden) Code() int {
	return 403
}

func (o *DecentralWebhookResourceDeleteDeleteForbidden) Error() string {
	return fmt.Sprintf("[DELETE /api/decentralWebhook/{id}][%d] decentralWebhookResourceDeleteDeleteForbidden ", 403)
}

func (o *DecentralWebhookResourceDeleteDeleteForbidden) String() string {
	return fmt.Sprintf("[DELETE /api/decentralWebhook/{id}][%d] decentralWebhookResourceDeleteDeleteForbidden ", 403)
}

func (o *DecentralWebhookResourceDeleteDeleteForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
