// Code generated by go-swagger; DO NOT EDIT.

package account_user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/leonnicolas/nupin/api/nuki/models"
)

// AccountUsersResourcePutPutReader is a Reader for the AccountUsersResourcePutPut structure.
type AccountUsersResourcePutPutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AccountUsersResourcePutPutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAccountUsersResourcePutPutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAccountUsersResourcePutPutBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /account/user] AccountUsersResource_put_put", response, response.Code())
	}
}

// NewAccountUsersResourcePutPutOK creates a AccountUsersResourcePutPutOK with default headers values
func NewAccountUsersResourcePutPutOK() *AccountUsersResourcePutPutOK {
	return &AccountUsersResourcePutPutOK{}
}

/*
AccountUsersResourcePutPutOK describes a response with status code 200, with default header values.

Ok
*/
type AccountUsersResourcePutPutOK struct {
	Payload *models.AccountUser
}

// IsSuccess returns true when this account users resource put put o k response has a 2xx status code
func (o *AccountUsersResourcePutPutOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this account users resource put put o k response has a 3xx status code
func (o *AccountUsersResourcePutPutOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this account users resource put put o k response has a 4xx status code
func (o *AccountUsersResourcePutPutOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this account users resource put put o k response has a 5xx status code
func (o *AccountUsersResourcePutPutOK) IsServerError() bool {
	return false
}

// IsCode returns true when this account users resource put put o k response a status code equal to that given
func (o *AccountUsersResourcePutPutOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the account users resource put put o k response
func (o *AccountUsersResourcePutPutOK) Code() int {
	return 200
}

func (o *AccountUsersResourcePutPutOK) Error() string {
	return fmt.Sprintf("[PUT /account/user][%d] accountUsersResourcePutPutOK  %+v", 200, o.Payload)
}

func (o *AccountUsersResourcePutPutOK) String() string {
	return fmt.Sprintf("[PUT /account/user][%d] accountUsersResourcePutPutOK  %+v", 200, o.Payload)
}

func (o *AccountUsersResourcePutPutOK) GetPayload() *models.AccountUser {
	return o.Payload
}

func (o *AccountUsersResourcePutPutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AccountUser)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAccountUsersResourcePutPutBadRequest creates a AccountUsersResourcePutPutBadRequest with default headers values
func NewAccountUsersResourcePutPutBadRequest() *AccountUsersResourcePutPutBadRequest {
	return &AccountUsersResourcePutPutBadRequest{}
}

/*
AccountUsersResourcePutPutBadRequest describes a response with status code 400, with default header values.

Invalid E-Mail address or name supplied
*/
type AccountUsersResourcePutPutBadRequest struct {
}

// IsSuccess returns true when this account users resource put put bad request response has a 2xx status code
func (o *AccountUsersResourcePutPutBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this account users resource put put bad request response has a 3xx status code
func (o *AccountUsersResourcePutPutBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this account users resource put put bad request response has a 4xx status code
func (o *AccountUsersResourcePutPutBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this account users resource put put bad request response has a 5xx status code
func (o *AccountUsersResourcePutPutBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this account users resource put put bad request response a status code equal to that given
func (o *AccountUsersResourcePutPutBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the account users resource put put bad request response
func (o *AccountUsersResourcePutPutBadRequest) Code() int {
	return 400
}

func (o *AccountUsersResourcePutPutBadRequest) Error() string {
	return fmt.Sprintf("[PUT /account/user][%d] accountUsersResourcePutPutBadRequest ", 400)
}

func (o *AccountUsersResourcePutPutBadRequest) String() string {
	return fmt.Sprintf("[PUT /account/user][%d] accountUsersResourcePutPutBadRequest ", 400)
}

func (o *AccountUsersResourcePutPutBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
