// Code generated by go-swagger; DO NOT EDIT.

package api_key

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// APIKeyAdvancedResourceDeleteDeleteReader is a Reader for the APIKeyAdvancedResourceDeleteDelete structure.
type APIKeyAdvancedResourceDeleteDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *APIKeyAdvancedResourceDeleteDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewAPIKeyAdvancedResourceDeleteDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewAPIKeyAdvancedResourceDeleteDeleteUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /api/key/{apiKeyId}/advanced] ApiKeyAdvancedResource_delete_delete", response, response.Code())
	}
}

// NewAPIKeyAdvancedResourceDeleteDeleteNoContent creates a APIKeyAdvancedResourceDeleteDeleteNoContent with default headers values
func NewAPIKeyAdvancedResourceDeleteDeleteNoContent() *APIKeyAdvancedResourceDeleteDeleteNoContent {
	return &APIKeyAdvancedResourceDeleteDeleteNoContent{}
}

/*
APIKeyAdvancedResourceDeleteDeleteNoContent describes a response with status code 204, with default header values.

Ok
*/
type APIKeyAdvancedResourceDeleteDeleteNoContent struct {
}

// IsSuccess returns true when this api key advanced resource delete delete no content response has a 2xx status code
func (o *APIKeyAdvancedResourceDeleteDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this api key advanced resource delete delete no content response has a 3xx status code
func (o *APIKeyAdvancedResourceDeleteDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this api key advanced resource delete delete no content response has a 4xx status code
func (o *APIKeyAdvancedResourceDeleteDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this api key advanced resource delete delete no content response has a 5xx status code
func (o *APIKeyAdvancedResourceDeleteDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this api key advanced resource delete delete no content response a status code equal to that given
func (o *APIKeyAdvancedResourceDeleteDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the api key advanced resource delete delete no content response
func (o *APIKeyAdvancedResourceDeleteDeleteNoContent) Code() int {
	return 204
}

func (o *APIKeyAdvancedResourceDeleteDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/key/{apiKeyId}/advanced][%d] apiKeyAdvancedResourceDeleteDeleteNoContent ", 204)
}

func (o *APIKeyAdvancedResourceDeleteDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /api/key/{apiKeyId}/advanced][%d] apiKeyAdvancedResourceDeleteDeleteNoContent ", 204)
}

func (o *APIKeyAdvancedResourceDeleteDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAPIKeyAdvancedResourceDeleteDeleteUnauthorized creates a APIKeyAdvancedResourceDeleteDeleteUnauthorized with default headers values
func NewAPIKeyAdvancedResourceDeleteDeleteUnauthorized() *APIKeyAdvancedResourceDeleteDeleteUnauthorized {
	return &APIKeyAdvancedResourceDeleteDeleteUnauthorized{}
}

/*
APIKeyAdvancedResourceDeleteDeleteUnauthorized describes a response with status code 401, with default header values.

Not authorized
*/
type APIKeyAdvancedResourceDeleteDeleteUnauthorized struct {
}

// IsSuccess returns true when this api key advanced resource delete delete unauthorized response has a 2xx status code
func (o *APIKeyAdvancedResourceDeleteDeleteUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this api key advanced resource delete delete unauthorized response has a 3xx status code
func (o *APIKeyAdvancedResourceDeleteDeleteUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this api key advanced resource delete delete unauthorized response has a 4xx status code
func (o *APIKeyAdvancedResourceDeleteDeleteUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this api key advanced resource delete delete unauthorized response has a 5xx status code
func (o *APIKeyAdvancedResourceDeleteDeleteUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this api key advanced resource delete delete unauthorized response a status code equal to that given
func (o *APIKeyAdvancedResourceDeleteDeleteUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the api key advanced resource delete delete unauthorized response
func (o *APIKeyAdvancedResourceDeleteDeleteUnauthorized) Code() int {
	return 401
}

func (o *APIKeyAdvancedResourceDeleteDeleteUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /api/key/{apiKeyId}/advanced][%d] apiKeyAdvancedResourceDeleteDeleteUnauthorized ", 401)
}

func (o *APIKeyAdvancedResourceDeleteDeleteUnauthorized) String() string {
	return fmt.Sprintf("[DELETE /api/key/{apiKeyId}/advanced][%d] apiKeyAdvancedResourceDeleteDeleteUnauthorized ", 401)
}

func (o *APIKeyAdvancedResourceDeleteDeleteUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
