// Code generated by go-swagger; DO NOT EDIT.

package api_key

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/leonnicolas/nupin/api/nuki/models"
)

// NewAPIKeysResourcePutPutParams creates a new APIKeysResourcePutPutParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAPIKeysResourcePutPutParams() *APIKeysResourcePutPutParams {
	return &APIKeysResourcePutPutParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAPIKeysResourcePutPutParamsWithTimeout creates a new APIKeysResourcePutPutParams object
// with the ability to set a timeout on a request.
func NewAPIKeysResourcePutPutParamsWithTimeout(timeout time.Duration) *APIKeysResourcePutPutParams {
	return &APIKeysResourcePutPutParams{
		timeout: timeout,
	}
}

// NewAPIKeysResourcePutPutParamsWithContext creates a new APIKeysResourcePutPutParams object
// with the ability to set a context for a request.
func NewAPIKeysResourcePutPutParamsWithContext(ctx context.Context) *APIKeysResourcePutPutParams {
	return &APIKeysResourcePutPutParams{
		Context: ctx,
	}
}

// NewAPIKeysResourcePutPutParamsWithHTTPClient creates a new APIKeysResourcePutPutParams object
// with the ability to set a custom HTTPClient for a request.
func NewAPIKeysResourcePutPutParamsWithHTTPClient(client *http.Client) *APIKeysResourcePutPutParams {
	return &APIKeysResourcePutPutParams{
		HTTPClient: client,
	}
}

/*
APIKeysResourcePutPutParams contains all the parameters to send to the API endpoint

	for the Api keys resource put put operation.

	Typically these are written to a http.Request.
*/
type APIKeysResourcePutPutParams struct {

	/* Body.

	   Api key create representation
	*/
	Body *models.APIKeyCreate

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the Api keys resource put put params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *APIKeysResourcePutPutParams) WithDefaults() *APIKeysResourcePutPutParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the Api keys resource put put params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *APIKeysResourcePutPutParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the Api keys resource put put params
func (o *APIKeysResourcePutPutParams) WithTimeout(timeout time.Duration) *APIKeysResourcePutPutParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the Api keys resource put put params
func (o *APIKeysResourcePutPutParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the Api keys resource put put params
func (o *APIKeysResourcePutPutParams) WithContext(ctx context.Context) *APIKeysResourcePutPutParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the Api keys resource put put params
func (o *APIKeysResourcePutPutParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the Api keys resource put put params
func (o *APIKeysResourcePutPutParams) WithHTTPClient(client *http.Client) *APIKeysResourcePutPutParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the Api keys resource put put params
func (o *APIKeysResourcePutPutParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the Api keys resource put put params
func (o *APIKeysResourcePutPutParams) WithBody(body *models.APIKeyCreate) *APIKeysResourcePutPutParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the Api keys resource put put params
func (o *APIKeysResourcePutPutParams) SetBody(body *models.APIKeyCreate) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *APIKeysResourcePutPutParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
