// Code generated by go-swagger; DO NOT EDIT.

package api_key

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/leonnicolas/nupin/api/nuki/models"
)

// APIKeyTokensResourceGetGetReader is a Reader for the APIKeyTokensResourceGetGet structure.
type APIKeyTokensResourceGetGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *APIKeyTokensResourceGetGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAPIKeyTokensResourceGetGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewAPIKeyTokensResourceGetGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/key/{apiKeyId}/token] ApiKeyTokensResource_get_get", response, response.Code())
	}
}

// NewAPIKeyTokensResourceGetGetOK creates a APIKeyTokensResourceGetGetOK with default headers values
func NewAPIKeyTokensResourceGetGetOK() *APIKeyTokensResourceGetGetOK {
	return &APIKeyTokensResourceGetGetOK{}
}

/*
APIKeyTokensResourceGetGetOK describes a response with status code 200, with default header values.

successful operation
*/
type APIKeyTokensResourceGetGetOK struct {
	Payload []*models.APIKeyToken
}

// IsSuccess returns true when this api key tokens resource get get o k response has a 2xx status code
func (o *APIKeyTokensResourceGetGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this api key tokens resource get get o k response has a 3xx status code
func (o *APIKeyTokensResourceGetGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this api key tokens resource get get o k response has a 4xx status code
func (o *APIKeyTokensResourceGetGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this api key tokens resource get get o k response has a 5xx status code
func (o *APIKeyTokensResourceGetGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this api key tokens resource get get o k response a status code equal to that given
func (o *APIKeyTokensResourceGetGetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the api key tokens resource get get o k response
func (o *APIKeyTokensResourceGetGetOK) Code() int {
	return 200
}

func (o *APIKeyTokensResourceGetGetOK) Error() string {
	return fmt.Sprintf("[GET /api/key/{apiKeyId}/token][%d] apiKeyTokensResourceGetGetOK  %+v", 200, o.Payload)
}

func (o *APIKeyTokensResourceGetGetOK) String() string {
	return fmt.Sprintf("[GET /api/key/{apiKeyId}/token][%d] apiKeyTokensResourceGetGetOK  %+v", 200, o.Payload)
}

func (o *APIKeyTokensResourceGetGetOK) GetPayload() []*models.APIKeyToken {
	return o.Payload
}

func (o *APIKeyTokensResourceGetGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAPIKeyTokensResourceGetGetUnauthorized creates a APIKeyTokensResourceGetGetUnauthorized with default headers values
func NewAPIKeyTokensResourceGetGetUnauthorized() *APIKeyTokensResourceGetGetUnauthorized {
	return &APIKeyTokensResourceGetGetUnauthorized{}
}

/*
APIKeyTokensResourceGetGetUnauthorized describes a response with status code 401, with default header values.

Not authorized
*/
type APIKeyTokensResourceGetGetUnauthorized struct {
}

// IsSuccess returns true when this api key tokens resource get get unauthorized response has a 2xx status code
func (o *APIKeyTokensResourceGetGetUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this api key tokens resource get get unauthorized response has a 3xx status code
func (o *APIKeyTokensResourceGetGetUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this api key tokens resource get get unauthorized response has a 4xx status code
func (o *APIKeyTokensResourceGetGetUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this api key tokens resource get get unauthorized response has a 5xx status code
func (o *APIKeyTokensResourceGetGetUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this api key tokens resource get get unauthorized response a status code equal to that given
func (o *APIKeyTokensResourceGetGetUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the api key tokens resource get get unauthorized response
func (o *APIKeyTokensResourceGetGetUnauthorized) Code() int {
	return 401
}

func (o *APIKeyTokensResourceGetGetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/key/{apiKeyId}/token][%d] apiKeyTokensResourceGetGetUnauthorized ", 401)
}

func (o *APIKeyTokensResourceGetGetUnauthorized) String() string {
	return fmt.Sprintf("[GET /api/key/{apiKeyId}/token][%d] apiKeyTokensResourceGetGetUnauthorized ", 401)
}

func (o *APIKeyTokensResourceGetGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
