// Code generated by go-swagger; DO NOT EDIT.

package api_key

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/leonnicolas/nupin/api/nuki/models"
)

// NewAPIKeyResourcePostPostParams creates a new APIKeyResourcePostPostParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAPIKeyResourcePostPostParams() *APIKeyResourcePostPostParams {
	return &APIKeyResourcePostPostParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAPIKeyResourcePostPostParamsWithTimeout creates a new APIKeyResourcePostPostParams object
// with the ability to set a timeout on a request.
func NewAPIKeyResourcePostPostParamsWithTimeout(timeout time.Duration) *APIKeyResourcePostPostParams {
	return &APIKeyResourcePostPostParams{
		timeout: timeout,
	}
}

// NewAPIKeyResourcePostPostParamsWithContext creates a new APIKeyResourcePostPostParams object
// with the ability to set a context for a request.
func NewAPIKeyResourcePostPostParamsWithContext(ctx context.Context) *APIKeyResourcePostPostParams {
	return &APIKeyResourcePostPostParams{
		Context: ctx,
	}
}

// NewAPIKeyResourcePostPostParamsWithHTTPClient creates a new APIKeyResourcePostPostParams object
// with the ability to set a custom HTTPClient for a request.
func NewAPIKeyResourcePostPostParamsWithHTTPClient(client *http.Client) *APIKeyResourcePostPostParams {
	return &APIKeyResourcePostPostParams{
		HTTPClient: client,
	}
}

/*
APIKeyResourcePostPostParams contains all the parameters to send to the API endpoint

	for the Api key resource post post operation.

	Typically these are written to a http.Request.
*/
type APIKeyResourcePostPostParams struct {

	/* APIKeyID.

	   The api key id
	*/
	APIKeyID int64

	/* Body.

	   Api key update representation
	*/
	Body *models.APIKeyUpdate

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the Api key resource post post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *APIKeyResourcePostPostParams) WithDefaults() *APIKeyResourcePostPostParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the Api key resource post post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *APIKeyResourcePostPostParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the Api key resource post post params
func (o *APIKeyResourcePostPostParams) WithTimeout(timeout time.Duration) *APIKeyResourcePostPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the Api key resource post post params
func (o *APIKeyResourcePostPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the Api key resource post post params
func (o *APIKeyResourcePostPostParams) WithContext(ctx context.Context) *APIKeyResourcePostPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the Api key resource post post params
func (o *APIKeyResourcePostPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the Api key resource post post params
func (o *APIKeyResourcePostPostParams) WithHTTPClient(client *http.Client) *APIKeyResourcePostPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the Api key resource post post params
func (o *APIKeyResourcePostPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIKeyID adds the aPIKeyID to the Api key resource post post params
func (o *APIKeyResourcePostPostParams) WithAPIKeyID(aPIKeyID int64) *APIKeyResourcePostPostParams {
	o.SetAPIKeyID(aPIKeyID)
	return o
}

// SetAPIKeyID adds the apiKeyId to the Api key resource post post params
func (o *APIKeyResourcePostPostParams) SetAPIKeyID(aPIKeyID int64) {
	o.APIKeyID = aPIKeyID
}

// WithBody adds the body to the Api key resource post post params
func (o *APIKeyResourcePostPostParams) WithBody(body *models.APIKeyUpdate) *APIKeyResourcePostPostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the Api key resource post post params
func (o *APIKeyResourcePostPostParams) SetBody(body *models.APIKeyUpdate) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *APIKeyResourcePostPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param apiKeyId
	if err := r.SetPathParam("apiKeyId", swag.FormatInt64(o.APIKeyID)); err != nil {
		return err
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
