// Code generated by go-swagger; DO NOT EDIT.

package smartlock

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// SmartlockLockActionResourcePostLockPostReader is a Reader for the SmartlockLockActionResourcePostLockPost structure.
type SmartlockLockActionResourcePostLockPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SmartlockLockActionResourcePostLockPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewSmartlockLockActionResourcePostLockPostNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSmartlockLockActionResourcePostLockPostBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewSmartlockLockActionResourcePostLockPostUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewSmartlockLockActionResourcePostLockPostMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /smartlock/{smartlockId}/action/lock] SmartlockLockActionResource_postLock_post", response, response.Code())
	}
}

// NewSmartlockLockActionResourcePostLockPostNoContent creates a SmartlockLockActionResourcePostLockPostNoContent with default headers values
func NewSmartlockLockActionResourcePostLockPostNoContent() *SmartlockLockActionResourcePostLockPostNoContent {
	return &SmartlockLockActionResourcePostLockPostNoContent{}
}

/*
SmartlockLockActionResourcePostLockPostNoContent describes a response with status code 204, with default header values.

Ok
*/
type SmartlockLockActionResourcePostLockPostNoContent struct {
}

// IsSuccess returns true when this smartlock lock action resource post lock post no content response has a 2xx status code
func (o *SmartlockLockActionResourcePostLockPostNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this smartlock lock action resource post lock post no content response has a 3xx status code
func (o *SmartlockLockActionResourcePostLockPostNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this smartlock lock action resource post lock post no content response has a 4xx status code
func (o *SmartlockLockActionResourcePostLockPostNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this smartlock lock action resource post lock post no content response has a 5xx status code
func (o *SmartlockLockActionResourcePostLockPostNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this smartlock lock action resource post lock post no content response a status code equal to that given
func (o *SmartlockLockActionResourcePostLockPostNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the smartlock lock action resource post lock post no content response
func (o *SmartlockLockActionResourcePostLockPostNoContent) Code() int {
	return 204
}

func (o *SmartlockLockActionResourcePostLockPostNoContent) Error() string {
	return fmt.Sprintf("[POST /smartlock/{smartlockId}/action/lock][%d] smartlockLockActionResourcePostLockPostNoContent ", 204)
}

func (o *SmartlockLockActionResourcePostLockPostNoContent) String() string {
	return fmt.Sprintf("[POST /smartlock/{smartlockId}/action/lock][%d] smartlockLockActionResourcePostLockPostNoContent ", 204)
}

func (o *SmartlockLockActionResourcePostLockPostNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSmartlockLockActionResourcePostLockPostBadRequest creates a SmartlockLockActionResourcePostLockPostBadRequest with default headers values
func NewSmartlockLockActionResourcePostLockPostBadRequest() *SmartlockLockActionResourcePostLockPostBadRequest {
	return &SmartlockLockActionResourcePostLockPostBadRequest{}
}

/*
SmartlockLockActionResourcePostLockPostBadRequest describes a response with status code 400, with default header values.

Bad Parameter
*/
type SmartlockLockActionResourcePostLockPostBadRequest struct {
}

// IsSuccess returns true when this smartlock lock action resource post lock post bad request response has a 2xx status code
func (o *SmartlockLockActionResourcePostLockPostBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this smartlock lock action resource post lock post bad request response has a 3xx status code
func (o *SmartlockLockActionResourcePostLockPostBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this smartlock lock action resource post lock post bad request response has a 4xx status code
func (o *SmartlockLockActionResourcePostLockPostBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this smartlock lock action resource post lock post bad request response has a 5xx status code
func (o *SmartlockLockActionResourcePostLockPostBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this smartlock lock action resource post lock post bad request response a status code equal to that given
func (o *SmartlockLockActionResourcePostLockPostBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the smartlock lock action resource post lock post bad request response
func (o *SmartlockLockActionResourcePostLockPostBadRequest) Code() int {
	return 400
}

func (o *SmartlockLockActionResourcePostLockPostBadRequest) Error() string {
	return fmt.Sprintf("[POST /smartlock/{smartlockId}/action/lock][%d] smartlockLockActionResourcePostLockPostBadRequest ", 400)
}

func (o *SmartlockLockActionResourcePostLockPostBadRequest) String() string {
	return fmt.Sprintf("[POST /smartlock/{smartlockId}/action/lock][%d] smartlockLockActionResourcePostLockPostBadRequest ", 400)
}

func (o *SmartlockLockActionResourcePostLockPostBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSmartlockLockActionResourcePostLockPostUnauthorized creates a SmartlockLockActionResourcePostLockPostUnauthorized with default headers values
func NewSmartlockLockActionResourcePostLockPostUnauthorized() *SmartlockLockActionResourcePostLockPostUnauthorized {
	return &SmartlockLockActionResourcePostLockPostUnauthorized{}
}

/*
SmartlockLockActionResourcePostLockPostUnauthorized describes a response with status code 401, with default header values.

Not authorized
*/
type SmartlockLockActionResourcePostLockPostUnauthorized struct {
}

// IsSuccess returns true when this smartlock lock action resource post lock post unauthorized response has a 2xx status code
func (o *SmartlockLockActionResourcePostLockPostUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this smartlock lock action resource post lock post unauthorized response has a 3xx status code
func (o *SmartlockLockActionResourcePostLockPostUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this smartlock lock action resource post lock post unauthorized response has a 4xx status code
func (o *SmartlockLockActionResourcePostLockPostUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this smartlock lock action resource post lock post unauthorized response has a 5xx status code
func (o *SmartlockLockActionResourcePostLockPostUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this smartlock lock action resource post lock post unauthorized response a status code equal to that given
func (o *SmartlockLockActionResourcePostLockPostUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the smartlock lock action resource post lock post unauthorized response
func (o *SmartlockLockActionResourcePostLockPostUnauthorized) Code() int {
	return 401
}

func (o *SmartlockLockActionResourcePostLockPostUnauthorized) Error() string {
	return fmt.Sprintf("[POST /smartlock/{smartlockId}/action/lock][%d] smartlockLockActionResourcePostLockPostUnauthorized ", 401)
}

func (o *SmartlockLockActionResourcePostLockPostUnauthorized) String() string {
	return fmt.Sprintf("[POST /smartlock/{smartlockId}/action/lock][%d] smartlockLockActionResourcePostLockPostUnauthorized ", 401)
}

func (o *SmartlockLockActionResourcePostLockPostUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSmartlockLockActionResourcePostLockPostMethodNotAllowed creates a SmartlockLockActionResourcePostLockPostMethodNotAllowed with default headers values
func NewSmartlockLockActionResourcePostLockPostMethodNotAllowed() *SmartlockLockActionResourcePostLockPostMethodNotAllowed {
	return &SmartlockLockActionResourcePostLockPostMethodNotAllowed{}
}

/*
SmartlockLockActionResourcePostLockPostMethodNotAllowed describes a response with status code 405, with default header values.

Not allowed
*/
type SmartlockLockActionResourcePostLockPostMethodNotAllowed struct {
}

// IsSuccess returns true when this smartlock lock action resource post lock post method not allowed response has a 2xx status code
func (o *SmartlockLockActionResourcePostLockPostMethodNotAllowed) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this smartlock lock action resource post lock post method not allowed response has a 3xx status code
func (o *SmartlockLockActionResourcePostLockPostMethodNotAllowed) IsRedirect() bool {
	return false
}

// IsClientError returns true when this smartlock lock action resource post lock post method not allowed response has a 4xx status code
func (o *SmartlockLockActionResourcePostLockPostMethodNotAllowed) IsClientError() bool {
	return true
}

// IsServerError returns true when this smartlock lock action resource post lock post method not allowed response has a 5xx status code
func (o *SmartlockLockActionResourcePostLockPostMethodNotAllowed) IsServerError() bool {
	return false
}

// IsCode returns true when this smartlock lock action resource post lock post method not allowed response a status code equal to that given
func (o *SmartlockLockActionResourcePostLockPostMethodNotAllowed) IsCode(code int) bool {
	return code == 405
}

// Code gets the status code for the smartlock lock action resource post lock post method not allowed response
func (o *SmartlockLockActionResourcePostLockPostMethodNotAllowed) Code() int {
	return 405
}

func (o *SmartlockLockActionResourcePostLockPostMethodNotAllowed) Error() string {
	return fmt.Sprintf("[POST /smartlock/{smartlockId}/action/lock][%d] smartlockLockActionResourcePostLockPostMethodNotAllowed ", 405)
}

func (o *SmartlockLockActionResourcePostLockPostMethodNotAllowed) String() string {
	return fmt.Sprintf("[POST /smartlock/{smartlockId}/action/lock][%d] smartlockLockActionResourcePostLockPostMethodNotAllowed ", 405)
}

func (o *SmartlockLockActionResourcePostLockPostMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
