// Code generated by go-swagger; DO NOT EDIT.

package smartlock

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// SmartdoorAdvancedConfigResourcePostPostReader is a Reader for the SmartdoorAdvancedConfigResourcePostPost structure.
type SmartdoorAdvancedConfigResourcePostPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SmartdoorAdvancedConfigResourcePostPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewSmartdoorAdvancedConfigResourcePostPostNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSmartdoorAdvancedConfigResourcePostPostBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewSmartdoorAdvancedConfigResourcePostPostUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /smartlock/{smartlockId}/advanced/smartdoorconfig] SmartdoorAdvancedConfigResource_post_post", response, response.Code())
	}
}

// NewSmartdoorAdvancedConfigResourcePostPostNoContent creates a SmartdoorAdvancedConfigResourcePostPostNoContent with default headers values
func NewSmartdoorAdvancedConfigResourcePostPostNoContent() *SmartdoorAdvancedConfigResourcePostPostNoContent {
	return &SmartdoorAdvancedConfigResourcePostPostNoContent{}
}

/*
SmartdoorAdvancedConfigResourcePostPostNoContent describes a response with status code 204, with default header values.

Ok
*/
type SmartdoorAdvancedConfigResourcePostPostNoContent struct {
}

// IsSuccess returns true when this smartdoor advanced config resource post post no content response has a 2xx status code
func (o *SmartdoorAdvancedConfigResourcePostPostNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this smartdoor advanced config resource post post no content response has a 3xx status code
func (o *SmartdoorAdvancedConfigResourcePostPostNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this smartdoor advanced config resource post post no content response has a 4xx status code
func (o *SmartdoorAdvancedConfigResourcePostPostNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this smartdoor advanced config resource post post no content response has a 5xx status code
func (o *SmartdoorAdvancedConfigResourcePostPostNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this smartdoor advanced config resource post post no content response a status code equal to that given
func (o *SmartdoorAdvancedConfigResourcePostPostNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the smartdoor advanced config resource post post no content response
func (o *SmartdoorAdvancedConfigResourcePostPostNoContent) Code() int {
	return 204
}

func (o *SmartdoorAdvancedConfigResourcePostPostNoContent) Error() string {
	return fmt.Sprintf("[POST /smartlock/{smartlockId}/advanced/smartdoorconfig][%d] smartdoorAdvancedConfigResourcePostPostNoContent ", 204)
}

func (o *SmartdoorAdvancedConfigResourcePostPostNoContent) String() string {
	return fmt.Sprintf("[POST /smartlock/{smartlockId}/advanced/smartdoorconfig][%d] smartdoorAdvancedConfigResourcePostPostNoContent ", 204)
}

func (o *SmartdoorAdvancedConfigResourcePostPostNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSmartdoorAdvancedConfigResourcePostPostBadRequest creates a SmartdoorAdvancedConfigResourcePostPostBadRequest with default headers values
func NewSmartdoorAdvancedConfigResourcePostPostBadRequest() *SmartdoorAdvancedConfigResourcePostPostBadRequest {
	return &SmartdoorAdvancedConfigResourcePostPostBadRequest{}
}

/*
SmartdoorAdvancedConfigResourcePostPostBadRequest describes a response with status code 400, with default header values.

Bad parameter
*/
type SmartdoorAdvancedConfigResourcePostPostBadRequest struct {
}

// IsSuccess returns true when this smartdoor advanced config resource post post bad request response has a 2xx status code
func (o *SmartdoorAdvancedConfigResourcePostPostBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this smartdoor advanced config resource post post bad request response has a 3xx status code
func (o *SmartdoorAdvancedConfigResourcePostPostBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this smartdoor advanced config resource post post bad request response has a 4xx status code
func (o *SmartdoorAdvancedConfigResourcePostPostBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this smartdoor advanced config resource post post bad request response has a 5xx status code
func (o *SmartdoorAdvancedConfigResourcePostPostBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this smartdoor advanced config resource post post bad request response a status code equal to that given
func (o *SmartdoorAdvancedConfigResourcePostPostBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the smartdoor advanced config resource post post bad request response
func (o *SmartdoorAdvancedConfigResourcePostPostBadRequest) Code() int {
	return 400
}

func (o *SmartdoorAdvancedConfigResourcePostPostBadRequest) Error() string {
	return fmt.Sprintf("[POST /smartlock/{smartlockId}/advanced/smartdoorconfig][%d] smartdoorAdvancedConfigResourcePostPostBadRequest ", 400)
}

func (o *SmartdoorAdvancedConfigResourcePostPostBadRequest) String() string {
	return fmt.Sprintf("[POST /smartlock/{smartlockId}/advanced/smartdoorconfig][%d] smartdoorAdvancedConfigResourcePostPostBadRequest ", 400)
}

func (o *SmartdoorAdvancedConfigResourcePostPostBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSmartdoorAdvancedConfigResourcePostPostUnauthorized creates a SmartdoorAdvancedConfigResourcePostPostUnauthorized with default headers values
func NewSmartdoorAdvancedConfigResourcePostPostUnauthorized() *SmartdoorAdvancedConfigResourcePostPostUnauthorized {
	return &SmartdoorAdvancedConfigResourcePostPostUnauthorized{}
}

/*
SmartdoorAdvancedConfigResourcePostPostUnauthorized describes a response with status code 401, with default header values.

Not authorized
*/
type SmartdoorAdvancedConfigResourcePostPostUnauthorized struct {
}

// IsSuccess returns true when this smartdoor advanced config resource post post unauthorized response has a 2xx status code
func (o *SmartdoorAdvancedConfigResourcePostPostUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this smartdoor advanced config resource post post unauthorized response has a 3xx status code
func (o *SmartdoorAdvancedConfigResourcePostPostUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this smartdoor advanced config resource post post unauthorized response has a 4xx status code
func (o *SmartdoorAdvancedConfigResourcePostPostUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this smartdoor advanced config resource post post unauthorized response has a 5xx status code
func (o *SmartdoorAdvancedConfigResourcePostPostUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this smartdoor advanced config resource post post unauthorized response a status code equal to that given
func (o *SmartdoorAdvancedConfigResourcePostPostUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the smartdoor advanced config resource post post unauthorized response
func (o *SmartdoorAdvancedConfigResourcePostPostUnauthorized) Code() int {
	return 401
}

func (o *SmartdoorAdvancedConfigResourcePostPostUnauthorized) Error() string {
	return fmt.Sprintf("[POST /smartlock/{smartlockId}/advanced/smartdoorconfig][%d] smartdoorAdvancedConfigResourcePostPostUnauthorized ", 401)
}

func (o *SmartdoorAdvancedConfigResourcePostPostUnauthorized) String() string {
	return fmt.Sprintf("[POST /smartlock/{smartlockId}/advanced/smartdoorconfig][%d] smartdoorAdvancedConfigResourcePostPostUnauthorized ", 401)
}

func (o *SmartdoorAdvancedConfigResourcePostPostUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
