// Code generated by go-swagger; DO NOT EDIT.

package smartlock

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// SmartlockAdminPinResourcePostPostReader is a Reader for the SmartlockAdminPinResourcePostPost structure.
type SmartlockAdminPinResourcePostPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SmartlockAdminPinResourcePostPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewSmartlockAdminPinResourcePostPostNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSmartlockAdminPinResourcePostPostBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewSmartlockAdminPinResourcePostPostUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /smartlock/{smartlockId}/admin/pin] SmartlockAdminPinResource_post_post", response, response.Code())
	}
}

// NewSmartlockAdminPinResourcePostPostNoContent creates a SmartlockAdminPinResourcePostPostNoContent with default headers values
func NewSmartlockAdminPinResourcePostPostNoContent() *SmartlockAdminPinResourcePostPostNoContent {
	return &SmartlockAdminPinResourcePostPostNoContent{}
}

/*
SmartlockAdminPinResourcePostPostNoContent describes a response with status code 204, with default header values.

Ok
*/
type SmartlockAdminPinResourcePostPostNoContent struct {
}

// IsSuccess returns true when this smartlock admin pin resource post post no content response has a 2xx status code
func (o *SmartlockAdminPinResourcePostPostNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this smartlock admin pin resource post post no content response has a 3xx status code
func (o *SmartlockAdminPinResourcePostPostNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this smartlock admin pin resource post post no content response has a 4xx status code
func (o *SmartlockAdminPinResourcePostPostNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this smartlock admin pin resource post post no content response has a 5xx status code
func (o *SmartlockAdminPinResourcePostPostNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this smartlock admin pin resource post post no content response a status code equal to that given
func (o *SmartlockAdminPinResourcePostPostNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the smartlock admin pin resource post post no content response
func (o *SmartlockAdminPinResourcePostPostNoContent) Code() int {
	return 204
}

func (o *SmartlockAdminPinResourcePostPostNoContent) Error() string {
	return fmt.Sprintf("[POST /smartlock/{smartlockId}/admin/pin][%d] smartlockAdminPinResourcePostPostNoContent ", 204)
}

func (o *SmartlockAdminPinResourcePostPostNoContent) String() string {
	return fmt.Sprintf("[POST /smartlock/{smartlockId}/admin/pin][%d] smartlockAdminPinResourcePostPostNoContent ", 204)
}

func (o *SmartlockAdminPinResourcePostPostNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSmartlockAdminPinResourcePostPostBadRequest creates a SmartlockAdminPinResourcePostPostBadRequest with default headers values
func NewSmartlockAdminPinResourcePostPostBadRequest() *SmartlockAdminPinResourcePostPostBadRequest {
	return &SmartlockAdminPinResourcePostPostBadRequest{}
}

/*
SmartlockAdminPinResourcePostPostBadRequest describes a response with status code 400, with default header values.

Bad parameter
*/
type SmartlockAdminPinResourcePostPostBadRequest struct {
}

// IsSuccess returns true when this smartlock admin pin resource post post bad request response has a 2xx status code
func (o *SmartlockAdminPinResourcePostPostBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this smartlock admin pin resource post post bad request response has a 3xx status code
func (o *SmartlockAdminPinResourcePostPostBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this smartlock admin pin resource post post bad request response has a 4xx status code
func (o *SmartlockAdminPinResourcePostPostBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this smartlock admin pin resource post post bad request response has a 5xx status code
func (o *SmartlockAdminPinResourcePostPostBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this smartlock admin pin resource post post bad request response a status code equal to that given
func (o *SmartlockAdminPinResourcePostPostBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the smartlock admin pin resource post post bad request response
func (o *SmartlockAdminPinResourcePostPostBadRequest) Code() int {
	return 400
}

func (o *SmartlockAdminPinResourcePostPostBadRequest) Error() string {
	return fmt.Sprintf("[POST /smartlock/{smartlockId}/admin/pin][%d] smartlockAdminPinResourcePostPostBadRequest ", 400)
}

func (o *SmartlockAdminPinResourcePostPostBadRequest) String() string {
	return fmt.Sprintf("[POST /smartlock/{smartlockId}/admin/pin][%d] smartlockAdminPinResourcePostPostBadRequest ", 400)
}

func (o *SmartlockAdminPinResourcePostPostBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSmartlockAdminPinResourcePostPostUnauthorized creates a SmartlockAdminPinResourcePostPostUnauthorized with default headers values
func NewSmartlockAdminPinResourcePostPostUnauthorized() *SmartlockAdminPinResourcePostPostUnauthorized {
	return &SmartlockAdminPinResourcePostPostUnauthorized{}
}

/*
SmartlockAdminPinResourcePostPostUnauthorized describes a response with status code 401, with default header values.

Not authorized
*/
type SmartlockAdminPinResourcePostPostUnauthorized struct {
}

// IsSuccess returns true when this smartlock admin pin resource post post unauthorized response has a 2xx status code
func (o *SmartlockAdminPinResourcePostPostUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this smartlock admin pin resource post post unauthorized response has a 3xx status code
func (o *SmartlockAdminPinResourcePostPostUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this smartlock admin pin resource post post unauthorized response has a 4xx status code
func (o *SmartlockAdminPinResourcePostPostUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this smartlock admin pin resource post post unauthorized response has a 5xx status code
func (o *SmartlockAdminPinResourcePostPostUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this smartlock admin pin resource post post unauthorized response a status code equal to that given
func (o *SmartlockAdminPinResourcePostPostUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the smartlock admin pin resource post post unauthorized response
func (o *SmartlockAdminPinResourcePostPostUnauthorized) Code() int {
	return 401
}

func (o *SmartlockAdminPinResourcePostPostUnauthorized) Error() string {
	return fmt.Sprintf("[POST /smartlock/{smartlockId}/admin/pin][%d] smartlockAdminPinResourcePostPostUnauthorized ", 401)
}

func (o *SmartlockAdminPinResourcePostPostUnauthorized) String() string {
	return fmt.Sprintf("[POST /smartlock/{smartlockId}/admin/pin][%d] smartlockAdminPinResourcePostPostUnauthorized ", 401)
}

func (o *SmartlockAdminPinResourcePostPostUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
