// Code generated by go-swagger; DO NOT EDIT.

package smartlock

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSmartlockLockActionResourcePostLockPostParams creates a new SmartlockLockActionResourcePostLockPostParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSmartlockLockActionResourcePostLockPostParams() *SmartlockLockActionResourcePostLockPostParams {
	return &SmartlockLockActionResourcePostLockPostParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSmartlockLockActionResourcePostLockPostParamsWithTimeout creates a new SmartlockLockActionResourcePostLockPostParams object
// with the ability to set a timeout on a request.
func NewSmartlockLockActionResourcePostLockPostParamsWithTimeout(timeout time.Duration) *SmartlockLockActionResourcePostLockPostParams {
	return &SmartlockLockActionResourcePostLockPostParams{
		timeout: timeout,
	}
}

// NewSmartlockLockActionResourcePostLockPostParamsWithContext creates a new SmartlockLockActionResourcePostLockPostParams object
// with the ability to set a context for a request.
func NewSmartlockLockActionResourcePostLockPostParamsWithContext(ctx context.Context) *SmartlockLockActionResourcePostLockPostParams {
	return &SmartlockLockActionResourcePostLockPostParams{
		Context: ctx,
	}
}

// NewSmartlockLockActionResourcePostLockPostParamsWithHTTPClient creates a new SmartlockLockActionResourcePostLockPostParams object
// with the ability to set a custom HTTPClient for a request.
func NewSmartlockLockActionResourcePostLockPostParamsWithHTTPClient(client *http.Client) *SmartlockLockActionResourcePostLockPostParams {
	return &SmartlockLockActionResourcePostLockPostParams{
		HTTPClient: client,
	}
}

/*
SmartlockLockActionResourcePostLockPostParams contains all the parameters to send to the API endpoint

	for the smartlock lock action resource post lock post operation.

	Typically these are written to a http.Request.
*/
type SmartlockLockActionResourcePostLockPostParams struct {

	/* SmartlockID.

	   The smartlock id
	*/
	SmartlockID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the smartlock lock action resource post lock post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SmartlockLockActionResourcePostLockPostParams) WithDefaults() *SmartlockLockActionResourcePostLockPostParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the smartlock lock action resource post lock post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SmartlockLockActionResourcePostLockPostParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the smartlock lock action resource post lock post params
func (o *SmartlockLockActionResourcePostLockPostParams) WithTimeout(timeout time.Duration) *SmartlockLockActionResourcePostLockPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the smartlock lock action resource post lock post params
func (o *SmartlockLockActionResourcePostLockPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the smartlock lock action resource post lock post params
func (o *SmartlockLockActionResourcePostLockPostParams) WithContext(ctx context.Context) *SmartlockLockActionResourcePostLockPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the smartlock lock action resource post lock post params
func (o *SmartlockLockActionResourcePostLockPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the smartlock lock action resource post lock post params
func (o *SmartlockLockActionResourcePostLockPostParams) WithHTTPClient(client *http.Client) *SmartlockLockActionResourcePostLockPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the smartlock lock action resource post lock post params
func (o *SmartlockLockActionResourcePostLockPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSmartlockID adds the smartlockID to the smartlock lock action resource post lock post params
func (o *SmartlockLockActionResourcePostLockPostParams) WithSmartlockID(smartlockID string) *SmartlockLockActionResourcePostLockPostParams {
	o.SetSmartlockID(smartlockID)
	return o
}

// SetSmartlockID adds the smartlockId to the smartlock lock action resource post lock post params
func (o *SmartlockLockActionResourcePostLockPostParams) SetSmartlockID(smartlockID string) {
	o.SmartlockID = smartlockID
}

// WriteToRequest writes these params to a swagger request
func (o *SmartlockLockActionResourcePostLockPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param smartlockId
	if err := r.SetPathParam("smartlockId", o.SmartlockID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
