// Code generated by go-swagger; DO NOT EDIT.

package smartlock

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// SmartlockOpenerAdvancedConfigResourcePostPostReader is a Reader for the SmartlockOpenerAdvancedConfigResourcePostPost structure.
type SmartlockOpenerAdvancedConfigResourcePostPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SmartlockOpenerAdvancedConfigResourcePostPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewSmartlockOpenerAdvancedConfigResourcePostPostNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSmartlockOpenerAdvancedConfigResourcePostPostBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewSmartlockOpenerAdvancedConfigResourcePostPostUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /smartlock/{smartlockId}/advanced/openerconfig] SmartlockOpenerAdvancedConfigResource_post_post", response, response.Code())
	}
}

// NewSmartlockOpenerAdvancedConfigResourcePostPostNoContent creates a SmartlockOpenerAdvancedConfigResourcePostPostNoContent with default headers values
func NewSmartlockOpenerAdvancedConfigResourcePostPostNoContent() *SmartlockOpenerAdvancedConfigResourcePostPostNoContent {
	return &SmartlockOpenerAdvancedConfigResourcePostPostNoContent{}
}

/*
SmartlockOpenerAdvancedConfigResourcePostPostNoContent describes a response with status code 204, with default header values.

Ok
*/
type SmartlockOpenerAdvancedConfigResourcePostPostNoContent struct {
}

// IsSuccess returns true when this smartlock opener advanced config resource post post no content response has a 2xx status code
func (o *SmartlockOpenerAdvancedConfigResourcePostPostNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this smartlock opener advanced config resource post post no content response has a 3xx status code
func (o *SmartlockOpenerAdvancedConfigResourcePostPostNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this smartlock opener advanced config resource post post no content response has a 4xx status code
func (o *SmartlockOpenerAdvancedConfigResourcePostPostNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this smartlock opener advanced config resource post post no content response has a 5xx status code
func (o *SmartlockOpenerAdvancedConfigResourcePostPostNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this smartlock opener advanced config resource post post no content response a status code equal to that given
func (o *SmartlockOpenerAdvancedConfigResourcePostPostNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the smartlock opener advanced config resource post post no content response
func (o *SmartlockOpenerAdvancedConfigResourcePostPostNoContent) Code() int {
	return 204
}

func (o *SmartlockOpenerAdvancedConfigResourcePostPostNoContent) Error() string {
	return fmt.Sprintf("[POST /smartlock/{smartlockId}/advanced/openerconfig][%d] smartlockOpenerAdvancedConfigResourcePostPostNoContent ", 204)
}

func (o *SmartlockOpenerAdvancedConfigResourcePostPostNoContent) String() string {
	return fmt.Sprintf("[POST /smartlock/{smartlockId}/advanced/openerconfig][%d] smartlockOpenerAdvancedConfigResourcePostPostNoContent ", 204)
}

func (o *SmartlockOpenerAdvancedConfigResourcePostPostNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSmartlockOpenerAdvancedConfigResourcePostPostBadRequest creates a SmartlockOpenerAdvancedConfigResourcePostPostBadRequest with default headers values
func NewSmartlockOpenerAdvancedConfigResourcePostPostBadRequest() *SmartlockOpenerAdvancedConfigResourcePostPostBadRequest {
	return &SmartlockOpenerAdvancedConfigResourcePostPostBadRequest{}
}

/*
SmartlockOpenerAdvancedConfigResourcePostPostBadRequest describes a response with status code 400, with default header values.

Bad parameter
*/
type SmartlockOpenerAdvancedConfigResourcePostPostBadRequest struct {
}

// IsSuccess returns true when this smartlock opener advanced config resource post post bad request response has a 2xx status code
func (o *SmartlockOpenerAdvancedConfigResourcePostPostBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this smartlock opener advanced config resource post post bad request response has a 3xx status code
func (o *SmartlockOpenerAdvancedConfigResourcePostPostBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this smartlock opener advanced config resource post post bad request response has a 4xx status code
func (o *SmartlockOpenerAdvancedConfigResourcePostPostBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this smartlock opener advanced config resource post post bad request response has a 5xx status code
func (o *SmartlockOpenerAdvancedConfigResourcePostPostBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this smartlock opener advanced config resource post post bad request response a status code equal to that given
func (o *SmartlockOpenerAdvancedConfigResourcePostPostBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the smartlock opener advanced config resource post post bad request response
func (o *SmartlockOpenerAdvancedConfigResourcePostPostBadRequest) Code() int {
	return 400
}

func (o *SmartlockOpenerAdvancedConfigResourcePostPostBadRequest) Error() string {
	return fmt.Sprintf("[POST /smartlock/{smartlockId}/advanced/openerconfig][%d] smartlockOpenerAdvancedConfigResourcePostPostBadRequest ", 400)
}

func (o *SmartlockOpenerAdvancedConfigResourcePostPostBadRequest) String() string {
	return fmt.Sprintf("[POST /smartlock/{smartlockId}/advanced/openerconfig][%d] smartlockOpenerAdvancedConfigResourcePostPostBadRequest ", 400)
}

func (o *SmartlockOpenerAdvancedConfigResourcePostPostBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSmartlockOpenerAdvancedConfigResourcePostPostUnauthorized creates a SmartlockOpenerAdvancedConfigResourcePostPostUnauthorized with default headers values
func NewSmartlockOpenerAdvancedConfigResourcePostPostUnauthorized() *SmartlockOpenerAdvancedConfigResourcePostPostUnauthorized {
	return &SmartlockOpenerAdvancedConfigResourcePostPostUnauthorized{}
}

/*
SmartlockOpenerAdvancedConfigResourcePostPostUnauthorized describes a response with status code 401, with default header values.

Not authorized
*/
type SmartlockOpenerAdvancedConfigResourcePostPostUnauthorized struct {
}

// IsSuccess returns true when this smartlock opener advanced config resource post post unauthorized response has a 2xx status code
func (o *SmartlockOpenerAdvancedConfigResourcePostPostUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this smartlock opener advanced config resource post post unauthorized response has a 3xx status code
func (o *SmartlockOpenerAdvancedConfigResourcePostPostUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this smartlock opener advanced config resource post post unauthorized response has a 4xx status code
func (o *SmartlockOpenerAdvancedConfigResourcePostPostUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this smartlock opener advanced config resource post post unauthorized response has a 5xx status code
func (o *SmartlockOpenerAdvancedConfigResourcePostPostUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this smartlock opener advanced config resource post post unauthorized response a status code equal to that given
func (o *SmartlockOpenerAdvancedConfigResourcePostPostUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the smartlock opener advanced config resource post post unauthorized response
func (o *SmartlockOpenerAdvancedConfigResourcePostPostUnauthorized) Code() int {
	return 401
}

func (o *SmartlockOpenerAdvancedConfigResourcePostPostUnauthorized) Error() string {
	return fmt.Sprintf("[POST /smartlock/{smartlockId}/advanced/openerconfig][%d] smartlockOpenerAdvancedConfigResourcePostPostUnauthorized ", 401)
}

func (o *SmartlockOpenerAdvancedConfigResourcePostPostUnauthorized) String() string {
	return fmt.Sprintf("[POST /smartlock/{smartlockId}/advanced/openerconfig][%d] smartlockOpenerAdvancedConfigResourcePostPostUnauthorized ", 401)
}

func (o *SmartlockOpenerAdvancedConfigResourcePostPostUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
