// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// AccountEmailVerifyResourcePostPostReader is a Reader for the AccountEmailVerifyResourcePostPost structure.
type AccountEmailVerifyResourcePostPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AccountEmailVerifyResourcePostPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewAccountEmailVerifyResourcePostPostNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAccountEmailVerifyResourcePostPostBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewAccountEmailVerifyResourcePostPostUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewAccountEmailVerifyResourcePostPostConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /account/email/verify] AccountEmailVerifyResource_post_post", response, response.Code())
	}
}

// NewAccountEmailVerifyResourcePostPostNoContent creates a AccountEmailVerifyResourcePostPostNoContent with default headers values
func NewAccountEmailVerifyResourcePostPostNoContent() *AccountEmailVerifyResourcePostPostNoContent {
	return &AccountEmailVerifyResourcePostPostNoContent{}
}

/*
AccountEmailVerifyResourcePostPostNoContent describes a response with status code 204, with default header values.

Ok
*/
type AccountEmailVerifyResourcePostPostNoContent struct {
}

// IsSuccess returns true when this account email verify resource post post no content response has a 2xx status code
func (o *AccountEmailVerifyResourcePostPostNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this account email verify resource post post no content response has a 3xx status code
func (o *AccountEmailVerifyResourcePostPostNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this account email verify resource post post no content response has a 4xx status code
func (o *AccountEmailVerifyResourcePostPostNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this account email verify resource post post no content response has a 5xx status code
func (o *AccountEmailVerifyResourcePostPostNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this account email verify resource post post no content response a status code equal to that given
func (o *AccountEmailVerifyResourcePostPostNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the account email verify resource post post no content response
func (o *AccountEmailVerifyResourcePostPostNoContent) Code() int {
	return 204
}

func (o *AccountEmailVerifyResourcePostPostNoContent) Error() string {
	return fmt.Sprintf("[POST /account/email/verify][%d] accountEmailVerifyResourcePostPostNoContent ", 204)
}

func (o *AccountEmailVerifyResourcePostPostNoContent) String() string {
	return fmt.Sprintf("[POST /account/email/verify][%d] accountEmailVerifyResourcePostPostNoContent ", 204)
}

func (o *AccountEmailVerifyResourcePostPostNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAccountEmailVerifyResourcePostPostBadRequest creates a AccountEmailVerifyResourcePostPostBadRequest with default headers values
func NewAccountEmailVerifyResourcePostPostBadRequest() *AccountEmailVerifyResourcePostPostBadRequest {
	return &AccountEmailVerifyResourcePostPostBadRequest{}
}

/*
AccountEmailVerifyResourcePostPostBadRequest describes a response with status code 400, with default header values.

Email not in valid format
*/
type AccountEmailVerifyResourcePostPostBadRequest struct {
}

// IsSuccess returns true when this account email verify resource post post bad request response has a 2xx status code
func (o *AccountEmailVerifyResourcePostPostBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this account email verify resource post post bad request response has a 3xx status code
func (o *AccountEmailVerifyResourcePostPostBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this account email verify resource post post bad request response has a 4xx status code
func (o *AccountEmailVerifyResourcePostPostBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this account email verify resource post post bad request response has a 5xx status code
func (o *AccountEmailVerifyResourcePostPostBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this account email verify resource post post bad request response a status code equal to that given
func (o *AccountEmailVerifyResourcePostPostBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the account email verify resource post post bad request response
func (o *AccountEmailVerifyResourcePostPostBadRequest) Code() int {
	return 400
}

func (o *AccountEmailVerifyResourcePostPostBadRequest) Error() string {
	return fmt.Sprintf("[POST /account/email/verify][%d] accountEmailVerifyResourcePostPostBadRequest ", 400)
}

func (o *AccountEmailVerifyResourcePostPostBadRequest) String() string {
	return fmt.Sprintf("[POST /account/email/verify][%d] accountEmailVerifyResourcePostPostBadRequest ", 400)
}

func (o *AccountEmailVerifyResourcePostPostBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAccountEmailVerifyResourcePostPostUnauthorized creates a AccountEmailVerifyResourcePostPostUnauthorized with default headers values
func NewAccountEmailVerifyResourcePostPostUnauthorized() *AccountEmailVerifyResourcePostPostUnauthorized {
	return &AccountEmailVerifyResourcePostPostUnauthorized{}
}

/*
AccountEmailVerifyResourcePostPostUnauthorized describes a response with status code 401, with default header values.

Not authorized
*/
type AccountEmailVerifyResourcePostPostUnauthorized struct {
}

// IsSuccess returns true when this account email verify resource post post unauthorized response has a 2xx status code
func (o *AccountEmailVerifyResourcePostPostUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this account email verify resource post post unauthorized response has a 3xx status code
func (o *AccountEmailVerifyResourcePostPostUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this account email verify resource post post unauthorized response has a 4xx status code
func (o *AccountEmailVerifyResourcePostPostUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this account email verify resource post post unauthorized response has a 5xx status code
func (o *AccountEmailVerifyResourcePostPostUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this account email verify resource post post unauthorized response a status code equal to that given
func (o *AccountEmailVerifyResourcePostPostUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the account email verify resource post post unauthorized response
func (o *AccountEmailVerifyResourcePostPostUnauthorized) Code() int {
	return 401
}

func (o *AccountEmailVerifyResourcePostPostUnauthorized) Error() string {
	return fmt.Sprintf("[POST /account/email/verify][%d] accountEmailVerifyResourcePostPostUnauthorized ", 401)
}

func (o *AccountEmailVerifyResourcePostPostUnauthorized) String() string {
	return fmt.Sprintf("[POST /account/email/verify][%d] accountEmailVerifyResourcePostPostUnauthorized ", 401)
}

func (o *AccountEmailVerifyResourcePostPostUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAccountEmailVerifyResourcePostPostConflict creates a AccountEmailVerifyResourcePostPostConflict with default headers values
func NewAccountEmailVerifyResourcePostPostConflict() *AccountEmailVerifyResourcePostPostConflict {
	return &AccountEmailVerifyResourcePostPostConflict{}
}

/*
AccountEmailVerifyResourcePostPostConflict describes a response with status code 409, with default header values.

Other account is already using the email
*/
type AccountEmailVerifyResourcePostPostConflict struct {
}

// IsSuccess returns true when this account email verify resource post post conflict response has a 2xx status code
func (o *AccountEmailVerifyResourcePostPostConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this account email verify resource post post conflict response has a 3xx status code
func (o *AccountEmailVerifyResourcePostPostConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this account email verify resource post post conflict response has a 4xx status code
func (o *AccountEmailVerifyResourcePostPostConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this account email verify resource post post conflict response has a 5xx status code
func (o *AccountEmailVerifyResourcePostPostConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this account email verify resource post post conflict response a status code equal to that given
func (o *AccountEmailVerifyResourcePostPostConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the account email verify resource post post conflict response
func (o *AccountEmailVerifyResourcePostPostConflict) Code() int {
	return 409
}

func (o *AccountEmailVerifyResourcePostPostConflict) Error() string {
	return fmt.Sprintf("[POST /account/email/verify][%d] accountEmailVerifyResourcePostPostConflict ", 409)
}

func (o *AccountEmailVerifyResourcePostPostConflict) String() string {
	return fmt.Sprintf("[POST /account/email/verify][%d] accountEmailVerifyResourcePostPostConflict ", 409)
}

func (o *AccountEmailVerifyResourcePostPostConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
