// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/leonnicolas/nupin/api/nuki/models"
)

// AccountsResourceGetGetReader is a Reader for the AccountsResourceGetGet structure.
type AccountsResourceGetGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AccountsResourceGetGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAccountsResourceGetGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewAccountsResourceGetGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /account] AccountsResource_get_get", response, response.Code())
	}
}

// NewAccountsResourceGetGetOK creates a AccountsResourceGetGetOK with default headers values
func NewAccountsResourceGetGetOK() *AccountsResourceGetGetOK {
	return &AccountsResourceGetGetOK{}
}

/*
AccountsResourceGetGetOK describes a response with status code 200, with default header values.

successful operation
*/
type AccountsResourceGetGetOK struct {
	Payload *models.MyAccount
}

// IsSuccess returns true when this accounts resource get get o k response has a 2xx status code
func (o *AccountsResourceGetGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this accounts resource get get o k response has a 3xx status code
func (o *AccountsResourceGetGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this accounts resource get get o k response has a 4xx status code
func (o *AccountsResourceGetGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this accounts resource get get o k response has a 5xx status code
func (o *AccountsResourceGetGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this accounts resource get get o k response a status code equal to that given
func (o *AccountsResourceGetGetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the accounts resource get get o k response
func (o *AccountsResourceGetGetOK) Code() int {
	return 200
}

func (o *AccountsResourceGetGetOK) Error() string {
	return fmt.Sprintf("[GET /account][%d] accountsResourceGetGetOK  %+v", 200, o.Payload)
}

func (o *AccountsResourceGetGetOK) String() string {
	return fmt.Sprintf("[GET /account][%d] accountsResourceGetGetOK  %+v", 200, o.Payload)
}

func (o *AccountsResourceGetGetOK) GetPayload() *models.MyAccount {
	return o.Payload
}

func (o *AccountsResourceGetGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MyAccount)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAccountsResourceGetGetUnauthorized creates a AccountsResourceGetGetUnauthorized with default headers values
func NewAccountsResourceGetGetUnauthorized() *AccountsResourceGetGetUnauthorized {
	return &AccountsResourceGetGetUnauthorized{}
}

/*
AccountsResourceGetGetUnauthorized describes a response with status code 401, with default header values.

Not authorized
*/
type AccountsResourceGetGetUnauthorized struct {
}

// IsSuccess returns true when this accounts resource get get unauthorized response has a 2xx status code
func (o *AccountsResourceGetGetUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this accounts resource get get unauthorized response has a 3xx status code
func (o *AccountsResourceGetGetUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this accounts resource get get unauthorized response has a 4xx status code
func (o *AccountsResourceGetGetUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this accounts resource get get unauthorized response has a 5xx status code
func (o *AccountsResourceGetGetUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this accounts resource get get unauthorized response a status code equal to that given
func (o *AccountsResourceGetGetUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the accounts resource get get unauthorized response
func (o *AccountsResourceGetGetUnauthorized) Code() int {
	return 401
}

func (o *AccountsResourceGetGetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /account][%d] accountsResourceGetGetUnauthorized ", 401)
}

func (o *AccountsResourceGetGetUnauthorized) String() string {
	return fmt.Sprintf("[GET /account][%d] accountsResourceGetGetUnauthorized ", 401)
}

func (o *AccountsResourceGetGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
