// Code generated by go-swagger; DO NOT EDIT.

package notification

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewNotificationsResourceGetGetParams creates a new NotificationsResourceGetGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewNotificationsResourceGetGetParams() *NotificationsResourceGetGetParams {
	return &NotificationsResourceGetGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewNotificationsResourceGetGetParamsWithTimeout creates a new NotificationsResourceGetGetParams object
// with the ability to set a timeout on a request.
func NewNotificationsResourceGetGetParamsWithTimeout(timeout time.Duration) *NotificationsResourceGetGetParams {
	return &NotificationsResourceGetGetParams{
		timeout: timeout,
	}
}

// NewNotificationsResourceGetGetParamsWithContext creates a new NotificationsResourceGetGetParams object
// with the ability to set a context for a request.
func NewNotificationsResourceGetGetParamsWithContext(ctx context.Context) *NotificationsResourceGetGetParams {
	return &NotificationsResourceGetGetParams{
		Context: ctx,
	}
}

// NewNotificationsResourceGetGetParamsWithHTTPClient creates a new NotificationsResourceGetGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewNotificationsResourceGetGetParamsWithHTTPClient(client *http.Client) *NotificationsResourceGetGetParams {
	return &NotificationsResourceGetGetParams{
		HTTPClient: client,
	}
}

/*
NotificationsResourceGetGetParams contains all the parameters to send to the API endpoint

	for the notifications resource get get operation.

	Typically these are written to a http.Request.
*/
type NotificationsResourceGetGetParams struct {

	/* ReferenceID.

	   The reference ID to the third party system
	*/
	ReferenceID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the notifications resource get get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NotificationsResourceGetGetParams) WithDefaults() *NotificationsResourceGetGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the notifications resource get get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NotificationsResourceGetGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the notifications resource get get params
func (o *NotificationsResourceGetGetParams) WithTimeout(timeout time.Duration) *NotificationsResourceGetGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the notifications resource get get params
func (o *NotificationsResourceGetGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the notifications resource get get params
func (o *NotificationsResourceGetGetParams) WithContext(ctx context.Context) *NotificationsResourceGetGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the notifications resource get get params
func (o *NotificationsResourceGetGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the notifications resource get get params
func (o *NotificationsResourceGetGetParams) WithHTTPClient(client *http.Client) *NotificationsResourceGetGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the notifications resource get get params
func (o *NotificationsResourceGetGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithReferenceID adds the referenceID to the notifications resource get get params
func (o *NotificationsResourceGetGetParams) WithReferenceID(referenceID *string) *NotificationsResourceGetGetParams {
	o.SetReferenceID(referenceID)
	return o
}

// SetReferenceID adds the referenceId to the notifications resource get get params
func (o *NotificationsResourceGetGetParams) SetReferenceID(referenceID *string) {
	o.ReferenceID = referenceID
}

// WriteToRequest writes these params to a swagger request
func (o *NotificationsResourceGetGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ReferenceID != nil {

		// query param referenceId
		var qrReferenceID string

		if o.ReferenceID != nil {
			qrReferenceID = *o.ReferenceID
		}
		qReferenceID := qrReferenceID
		if qReferenceID != "" {

			if err := r.SetQueryParam("referenceId", qReferenceID); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
