// Code generated by go-swagger; DO NOT EDIT.

package notification

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/leonnicolas/nupin/api/nuki/models"
)

// NewNotificationResourcePostPostParams creates a new NotificationResourcePostPostParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewNotificationResourcePostPostParams() *NotificationResourcePostPostParams {
	return &NotificationResourcePostPostParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewNotificationResourcePostPostParamsWithTimeout creates a new NotificationResourcePostPostParams object
// with the ability to set a timeout on a request.
func NewNotificationResourcePostPostParamsWithTimeout(timeout time.Duration) *NotificationResourcePostPostParams {
	return &NotificationResourcePostPostParams{
		timeout: timeout,
	}
}

// NewNotificationResourcePostPostParamsWithContext creates a new NotificationResourcePostPostParams object
// with the ability to set a context for a request.
func NewNotificationResourcePostPostParamsWithContext(ctx context.Context) *NotificationResourcePostPostParams {
	return &NotificationResourcePostPostParams{
		Context: ctx,
	}
}

// NewNotificationResourcePostPostParamsWithHTTPClient creates a new NotificationResourcePostPostParams object
// with the ability to set a custom HTTPClient for a request.
func NewNotificationResourcePostPostParamsWithHTTPClient(client *http.Client) *NotificationResourcePostPostParams {
	return &NotificationResourcePostPostParams{
		HTTPClient: client,
	}
}

/*
NotificationResourcePostPostParams contains all the parameters to send to the API endpoint

	for the notification resource post post operation.

	Typically these are written to a http.Request.
*/
type NotificationResourcePostPostParams struct {

	/* Body.

	   Notification update representation
	*/
	Body *models.Notification

	/* NotificationID.

	   The unique notification ID
	*/
	NotificationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the notification resource post post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NotificationResourcePostPostParams) WithDefaults() *NotificationResourcePostPostParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the notification resource post post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NotificationResourcePostPostParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the notification resource post post params
func (o *NotificationResourcePostPostParams) WithTimeout(timeout time.Duration) *NotificationResourcePostPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the notification resource post post params
func (o *NotificationResourcePostPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the notification resource post post params
func (o *NotificationResourcePostPostParams) WithContext(ctx context.Context) *NotificationResourcePostPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the notification resource post post params
func (o *NotificationResourcePostPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the notification resource post post params
func (o *NotificationResourcePostPostParams) WithHTTPClient(client *http.Client) *NotificationResourcePostPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the notification resource post post params
func (o *NotificationResourcePostPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the notification resource post post params
func (o *NotificationResourcePostPostParams) WithBody(body *models.Notification) *NotificationResourcePostPostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the notification resource post post params
func (o *NotificationResourcePostPostParams) SetBody(body *models.Notification) {
	o.Body = body
}

// WithNotificationID adds the notificationID to the notification resource post post params
func (o *NotificationResourcePostPostParams) WithNotificationID(notificationID string) *NotificationResourcePostPostParams {
	o.SetNotificationID(notificationID)
	return o
}

// SetNotificationID adds the notificationId to the notification resource post post params
func (o *NotificationResourcePostPostParams) SetNotificationID(notificationID string) {
	o.NotificationID = notificationID
}

// WriteToRequest writes these params to a swagger request
func (o *NotificationResourcePostPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param notificationId
	if err := r.SetPathParam("notificationId", o.NotificationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
