// Code generated by go-swagger; DO NOT EDIT.

package address

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/leonnicolas/nupin/api/nuki/models"
)

// AddressUnitResourceDeleteDeleteReader is a Reader for the AddressUnitResourceDeleteDelete structure.
type AddressUnitResourceDeleteDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddressUnitResourceDeleteDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddressUnitResourceDeleteDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewAddressUnitResourceDeleteDeleteUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewAddressUnitResourceDeleteDeleteForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 423:
		result := NewAddressUnitResourceDeleteDeleteLocked()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /address/{addressId}/unit/{id}] AddressUnitResource_delete_delete", response, response.Code())
	}
}

// NewAddressUnitResourceDeleteDeleteOK creates a AddressUnitResourceDeleteDeleteOK with default headers values
func NewAddressUnitResourceDeleteDeleteOK() *AddressUnitResourceDeleteDeleteOK {
	return &AddressUnitResourceDeleteDeleteOK{}
}

/*
AddressUnitResourceDeleteDeleteOK describes a response with status code 200, with default header values.

Ok
*/
type AddressUnitResourceDeleteDeleteOK struct {
	Payload *models.AdvancedConfirmationResponse
}

// IsSuccess returns true when this address unit resource delete delete o k response has a 2xx status code
func (o *AddressUnitResourceDeleteDeleteOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this address unit resource delete delete o k response has a 3xx status code
func (o *AddressUnitResourceDeleteDeleteOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this address unit resource delete delete o k response has a 4xx status code
func (o *AddressUnitResourceDeleteDeleteOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this address unit resource delete delete o k response has a 5xx status code
func (o *AddressUnitResourceDeleteDeleteOK) IsServerError() bool {
	return false
}

// IsCode returns true when this address unit resource delete delete o k response a status code equal to that given
func (o *AddressUnitResourceDeleteDeleteOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the address unit resource delete delete o k response
func (o *AddressUnitResourceDeleteDeleteOK) Code() int {
	return 200
}

func (o *AddressUnitResourceDeleteDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /address/{addressId}/unit/{id}][%d] addressUnitResourceDeleteDeleteOK  %+v", 200, o.Payload)
}

func (o *AddressUnitResourceDeleteDeleteOK) String() string {
	return fmt.Sprintf("[DELETE /address/{addressId}/unit/{id}][%d] addressUnitResourceDeleteDeleteOK  %+v", 200, o.Payload)
}

func (o *AddressUnitResourceDeleteDeleteOK) GetPayload() *models.AdvancedConfirmationResponse {
	return o.Payload
}

func (o *AddressUnitResourceDeleteDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AdvancedConfirmationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddressUnitResourceDeleteDeleteUnauthorized creates a AddressUnitResourceDeleteDeleteUnauthorized with default headers values
func NewAddressUnitResourceDeleteDeleteUnauthorized() *AddressUnitResourceDeleteDeleteUnauthorized {
	return &AddressUnitResourceDeleteDeleteUnauthorized{}
}

/*
AddressUnitResourceDeleteDeleteUnauthorized describes a response with status code 401, with default header values.

Not authorized
*/
type AddressUnitResourceDeleteDeleteUnauthorized struct {
}

// IsSuccess returns true when this address unit resource delete delete unauthorized response has a 2xx status code
func (o *AddressUnitResourceDeleteDeleteUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this address unit resource delete delete unauthorized response has a 3xx status code
func (o *AddressUnitResourceDeleteDeleteUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this address unit resource delete delete unauthorized response has a 4xx status code
func (o *AddressUnitResourceDeleteDeleteUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this address unit resource delete delete unauthorized response has a 5xx status code
func (o *AddressUnitResourceDeleteDeleteUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this address unit resource delete delete unauthorized response a status code equal to that given
func (o *AddressUnitResourceDeleteDeleteUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the address unit resource delete delete unauthorized response
func (o *AddressUnitResourceDeleteDeleteUnauthorized) Code() int {
	return 401
}

func (o *AddressUnitResourceDeleteDeleteUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /address/{addressId}/unit/{id}][%d] addressUnitResourceDeleteDeleteUnauthorized ", 401)
}

func (o *AddressUnitResourceDeleteDeleteUnauthorized) String() string {
	return fmt.Sprintf("[DELETE /address/{addressId}/unit/{id}][%d] addressUnitResourceDeleteDeleteUnauthorized ", 401)
}

func (o *AddressUnitResourceDeleteDeleteUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddressUnitResourceDeleteDeleteForbidden creates a AddressUnitResourceDeleteDeleteForbidden with default headers values
func NewAddressUnitResourceDeleteDeleteForbidden() *AddressUnitResourceDeleteDeleteForbidden {
	return &AddressUnitResourceDeleteDeleteForbidden{}
}

/*
AddressUnitResourceDeleteDeleteForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type AddressUnitResourceDeleteDeleteForbidden struct {
}

// IsSuccess returns true when this address unit resource delete delete forbidden response has a 2xx status code
func (o *AddressUnitResourceDeleteDeleteForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this address unit resource delete delete forbidden response has a 3xx status code
func (o *AddressUnitResourceDeleteDeleteForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this address unit resource delete delete forbidden response has a 4xx status code
func (o *AddressUnitResourceDeleteDeleteForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this address unit resource delete delete forbidden response has a 5xx status code
func (o *AddressUnitResourceDeleteDeleteForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this address unit resource delete delete forbidden response a status code equal to that given
func (o *AddressUnitResourceDeleteDeleteForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the address unit resource delete delete forbidden response
func (o *AddressUnitResourceDeleteDeleteForbidden) Code() int {
	return 403
}

func (o *AddressUnitResourceDeleteDeleteForbidden) Error() string {
	return fmt.Sprintf("[DELETE /address/{addressId}/unit/{id}][%d] addressUnitResourceDeleteDeleteForbidden ", 403)
}

func (o *AddressUnitResourceDeleteDeleteForbidden) String() string {
	return fmt.Sprintf("[DELETE /address/{addressId}/unit/{id}][%d] addressUnitResourceDeleteDeleteForbidden ", 403)
}

func (o *AddressUnitResourceDeleteDeleteForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddressUnitResourceDeleteDeleteLocked creates a AddressUnitResourceDeleteDeleteLocked with default headers values
func NewAddressUnitResourceDeleteDeleteLocked() *AddressUnitResourceDeleteDeleteLocked {
	return &AddressUnitResourceDeleteDeleteLocked{}
}

/*
AddressUnitResourceDeleteDeleteLocked describes a response with status code 423, with default header values.

Locked
*/
type AddressUnitResourceDeleteDeleteLocked struct {
}

// IsSuccess returns true when this address unit resource delete delete locked response has a 2xx status code
func (o *AddressUnitResourceDeleteDeleteLocked) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this address unit resource delete delete locked response has a 3xx status code
func (o *AddressUnitResourceDeleteDeleteLocked) IsRedirect() bool {
	return false
}

// IsClientError returns true when this address unit resource delete delete locked response has a 4xx status code
func (o *AddressUnitResourceDeleteDeleteLocked) IsClientError() bool {
	return true
}

// IsServerError returns true when this address unit resource delete delete locked response has a 5xx status code
func (o *AddressUnitResourceDeleteDeleteLocked) IsServerError() bool {
	return false
}

// IsCode returns true when this address unit resource delete delete locked response a status code equal to that given
func (o *AddressUnitResourceDeleteDeleteLocked) IsCode(code int) bool {
	return code == 423
}

// Code gets the status code for the address unit resource delete delete locked response
func (o *AddressUnitResourceDeleteDeleteLocked) Code() int {
	return 423
}

func (o *AddressUnitResourceDeleteDeleteLocked) Error() string {
	return fmt.Sprintf("[DELETE /address/{addressId}/unit/{id}][%d] addressUnitResourceDeleteDeleteLocked ", 423)
}

func (o *AddressUnitResourceDeleteDeleteLocked) String() string {
	return fmt.Sprintf("[DELETE /address/{addressId}/unit/{id}][%d] addressUnitResourceDeleteDeleteLocked ", 423)
}

func (o *AddressUnitResourceDeleteDeleteLocked) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
