// Code generated by go-swagger; DO NOT EDIT.

package address

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/leonnicolas/nupin/api/nuki/models"
)

// AddressUnitsResourcePutPutReader is a Reader for the AddressUnitsResourcePutPut structure.
type AddressUnitsResourcePutPutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddressUnitsResourcePutPutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddressUnitsResourcePutPutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAddressUnitsResourcePutPutBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewAddressUnitsResourcePutPutUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewAddressUnitsResourcePutPutForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /address/{addressId}/unit] AddressUnitsResource_put_put", response, response.Code())
	}
}

// NewAddressUnitsResourcePutPutOK creates a AddressUnitsResourcePutPutOK with default headers values
func NewAddressUnitsResourcePutPutOK() *AddressUnitsResourcePutPutOK {
	return &AddressUnitsResourcePutPutOK{}
}

/*
AddressUnitsResourcePutPutOK describes a response with status code 200, with default header values.

Ok
*/
type AddressUnitsResourcePutPutOK struct {
	Payload *models.AddressUnitResponse
}

// IsSuccess returns true when this address units resource put put o k response has a 2xx status code
func (o *AddressUnitsResourcePutPutOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this address units resource put put o k response has a 3xx status code
func (o *AddressUnitsResourcePutPutOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this address units resource put put o k response has a 4xx status code
func (o *AddressUnitsResourcePutPutOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this address units resource put put o k response has a 5xx status code
func (o *AddressUnitsResourcePutPutOK) IsServerError() bool {
	return false
}

// IsCode returns true when this address units resource put put o k response a status code equal to that given
func (o *AddressUnitsResourcePutPutOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the address units resource put put o k response
func (o *AddressUnitsResourcePutPutOK) Code() int {
	return 200
}

func (o *AddressUnitsResourcePutPutOK) Error() string {
	return fmt.Sprintf("[PUT /address/{addressId}/unit][%d] addressUnitsResourcePutPutOK  %+v", 200, o.Payload)
}

func (o *AddressUnitsResourcePutPutOK) String() string {
	return fmt.Sprintf("[PUT /address/{addressId}/unit][%d] addressUnitsResourcePutPutOK  %+v", 200, o.Payload)
}

func (o *AddressUnitsResourcePutPutOK) GetPayload() *models.AddressUnitResponse {
	return o.Payload
}

func (o *AddressUnitsResourcePutPutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AddressUnitResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddressUnitsResourcePutPutBadRequest creates a AddressUnitsResourcePutPutBadRequest with default headers values
func NewAddressUnitsResourcePutPutBadRequest() *AddressUnitsResourcePutPutBadRequest {
	return &AddressUnitsResourcePutPutBadRequest{}
}

/*
AddressUnitsResourcePutPutBadRequest describes a response with status code 400, with default header values.

Bad Parameter
*/
type AddressUnitsResourcePutPutBadRequest struct {
}

// IsSuccess returns true when this address units resource put put bad request response has a 2xx status code
func (o *AddressUnitsResourcePutPutBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this address units resource put put bad request response has a 3xx status code
func (o *AddressUnitsResourcePutPutBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this address units resource put put bad request response has a 4xx status code
func (o *AddressUnitsResourcePutPutBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this address units resource put put bad request response has a 5xx status code
func (o *AddressUnitsResourcePutPutBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this address units resource put put bad request response a status code equal to that given
func (o *AddressUnitsResourcePutPutBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the address units resource put put bad request response
func (o *AddressUnitsResourcePutPutBadRequest) Code() int {
	return 400
}

func (o *AddressUnitsResourcePutPutBadRequest) Error() string {
	return fmt.Sprintf("[PUT /address/{addressId}/unit][%d] addressUnitsResourcePutPutBadRequest ", 400)
}

func (o *AddressUnitsResourcePutPutBadRequest) String() string {
	return fmt.Sprintf("[PUT /address/{addressId}/unit][%d] addressUnitsResourcePutPutBadRequest ", 400)
}

func (o *AddressUnitsResourcePutPutBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddressUnitsResourcePutPutUnauthorized creates a AddressUnitsResourcePutPutUnauthorized with default headers values
func NewAddressUnitsResourcePutPutUnauthorized() *AddressUnitsResourcePutPutUnauthorized {
	return &AddressUnitsResourcePutPutUnauthorized{}
}

/*
AddressUnitsResourcePutPutUnauthorized describes a response with status code 401, with default header values.

Not authorized
*/
type AddressUnitsResourcePutPutUnauthorized struct {
}

// IsSuccess returns true when this address units resource put put unauthorized response has a 2xx status code
func (o *AddressUnitsResourcePutPutUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this address units resource put put unauthorized response has a 3xx status code
func (o *AddressUnitsResourcePutPutUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this address units resource put put unauthorized response has a 4xx status code
func (o *AddressUnitsResourcePutPutUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this address units resource put put unauthorized response has a 5xx status code
func (o *AddressUnitsResourcePutPutUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this address units resource put put unauthorized response a status code equal to that given
func (o *AddressUnitsResourcePutPutUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the address units resource put put unauthorized response
func (o *AddressUnitsResourcePutPutUnauthorized) Code() int {
	return 401
}

func (o *AddressUnitsResourcePutPutUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /address/{addressId}/unit][%d] addressUnitsResourcePutPutUnauthorized ", 401)
}

func (o *AddressUnitsResourcePutPutUnauthorized) String() string {
	return fmt.Sprintf("[PUT /address/{addressId}/unit][%d] addressUnitsResourcePutPutUnauthorized ", 401)
}

func (o *AddressUnitsResourcePutPutUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddressUnitsResourcePutPutForbidden creates a AddressUnitsResourcePutPutForbidden with default headers values
func NewAddressUnitsResourcePutPutForbidden() *AddressUnitsResourcePutPutForbidden {
	return &AddressUnitsResourcePutPutForbidden{}
}

/*
AddressUnitsResourcePutPutForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type AddressUnitsResourcePutPutForbidden struct {
}

// IsSuccess returns true when this address units resource put put forbidden response has a 2xx status code
func (o *AddressUnitsResourcePutPutForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this address units resource put put forbidden response has a 3xx status code
func (o *AddressUnitsResourcePutPutForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this address units resource put put forbidden response has a 4xx status code
func (o *AddressUnitsResourcePutPutForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this address units resource put put forbidden response has a 5xx status code
func (o *AddressUnitsResourcePutPutForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this address units resource put put forbidden response a status code equal to that given
func (o *AddressUnitsResourcePutPutForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the address units resource put put forbidden response
func (o *AddressUnitsResourcePutPutForbidden) Code() int {
	return 403
}

func (o *AddressUnitsResourcePutPutForbidden) Error() string {
	return fmt.Sprintf("[PUT /address/{addressId}/unit][%d] addressUnitsResourcePutPutForbidden ", 403)
}

func (o *AddressUnitsResourcePutPutForbidden) String() string {
	return fmt.Sprintf("[PUT /address/{addressId}/unit][%d] addressUnitsResourcePutPutForbidden ", 403)
}

func (o *AddressUnitsResourcePutPutForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
